### ISSUE TITLE
setMasterPassword: Method "CreateItem" doesn't exist

### ISSUE THREAD

**Issue by JKatzwinkel** [mpdeimos/org.eclipse.equinox.security.linux#1]
I felt lucky stumbling upon your `secureStorage` extension when I needed an implementation for an E4 project. Unfortunately, when it comes to using `SecurePreferences` and your `LinuxProvider` jumps in, it seems to fail to communicate over DBus, ultimatively resulting in a `SecurityException`:

```
!ENTRY org.eclipse.equinox.security 1 0 2015-01-08 15:37:33.302
!MESSAGE New secure storage master password was generated (DBus Secret Service integration module). 
process 5361: arguments to dbus_message_unref() were incorrect, assertion "message != NULL" failed in file dbus-message.c line 1395.
This is normally a bug in some application using the D-Bus library.

!ENTRY org.eclipse.equinox.security 4 0 2015-01-08 15:37:33.305
!MESSAGE Secure storage was unable to save the master password.
!STACK 0
java.lang.SecurityException: Error receiving message: org.freedesktop.DBus.Error.UnknownMethod: Method "CreateItem" with signature "a{sv}(oayays)b" on interface "org.freedesktop.Secret.Collection" doesn't exist

at org.eclipse.equinox.internal.security.linux.LinuxProvider.setMasterPassword(Native Method)
at org.eclipse.equinox.internal.security.linux.LinuxProvider.createAndStorePassword(LinuxProvider.java:86)
at org.eclipse.equinox.internal.security.linux.LinuxProvider.getPassword(LinuxProvider.java:65)
```

I have `libdbus-1-dev` and `libdbus-1-3` installed, both version 1.2.16-2ubuntu4.8. My eclipse's Equinox security package is in version 1.2.0.v20130424-1801.

**Comment by mpdeimos** [comment]
Thanks for the report. What's your ubuntu version, so I can try to reproduce?

**Comment by JKatzwinkel** [comment]
Thanks for the quick reply! Admittedly, the problem might be connected to my ubuntu version being slightly dated: 10.04 LTS (lucid), with kernel 3.15.0-031500rc2-generic on x86. Gnome 2.30.2 (although apparently not relevant). I used your eclipse update site for installation.

**Comment by mpdeimos** [comment]
I fear that this is related to an outdated dbus secure service implementation of your dist (this might be related to gnome, as gnome keyring provides the secret service implementation over dbus).

The keyring implementation changed from Gnome 2 to 3, please refer to e.g. https://bugs.launchpad.net/ubuntu/+source/python-launchpadlib/+bug/745540/comments/25
Given the fact that Lucid reaches end of support in a few months, I'm not sure if it's worth setting up a VM and debug the error. However, maybe the implementation that is proposed in this Eclipse Bug might work for your setup: https://bugs.eclipse.org/bugs/show_bug.cgi?id=234509

**Comment by JKatzwinkel** [comment]
I briefly tried to update to a newer libdbus version, but came to the conclusion that making this work on a system that old is probably pointless. The patches offered at the bug report you linked didn't work for me, either. I will try your implementation with newer distros shortly.

**Comment by mpdeimos** [comment]
Sounds good.
